services:
  website:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      SMTP_HOST: ${SMTP_HOST:-smtp.ionos.de}
      SMTP_PORT: ${SMTP_PORT:-587}
      SMTP_TIMEOUT: ${SMTP_TIMEOUT:-10}
      SMTP_USER: ${SMTP_USER:-}
      SMTP_PASSWORD: ${SMTP_PASSWORD:-}
      SMTP_USE_TLS: ${SMTP_USE_TLS:-true}
      MAIL_FROM: ${MAIL_FROM:-kontakt@kuehnel-systems.de}
      MAIL_TO: ${MAIL_TO:-kontakt@kuehnel-systems.de}
    restart: unless-stopped
